version: '2'
services:
  testproddatabase-app:
    image: testproddatabase
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://testproddatabase-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=testProdDatabase
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  testproddatabase-mongodb:
    extends:
      file: mongodb.yml
      service: testproddatabase-mongodb
